/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.ControlVista;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author YorgenGalvis
 */
public class view extends javax.swing.JFrame {

    /**
     * Creates new form view
     */
    private ControlVista control=new ControlVista();
    private DefaultListModel modeloLista = new DefaultListModel();
    private DefaultListModel modeloListaProductos = new DefaultListModel();
    String seleccionado=null, seleccionadosp=null;
    
    
    public view() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.jPanelInformacion.setVisible(false);
        this.jListProductos.setVisible(false);
        this.btnAdSucursal.setVisible(false);
        this.jPanelLineaProducto.setVisible(false);
        this.jListSucursales.setModel(modeloLista);
        this.jListProductos.setModel(modeloListaProductos);
        this.btnDeleteSucursal.setVisible(false);
        this.btnMasAntiguo.setVisible(false);
        this.btnSucursales.setVisible(false);
    }
    
    
    public void mostrarSucursales(){
        if (modeloLista.getSize() > 0) {
            this.btnDeleteSucursal.setVisible(true);
            this.btnSucursales.setVisible(true);
        } else {
           this.btnDeleteSucursal.setVisible(false);
        }
        this.btnMasAntiguo.setVisible(false);
        modeloLista.clear();
     String lista = this.control.listarSucursales();
     String partes[] = lista.split(";");
        for (int i = 0; i < partes.length; i++) {
            String dato = partes[i];
            modeloLista.addElement(dato);
        }
    }
    
    public void mostrarProductosSucursal(){
        if (modeloLista.getSize() > 0) {
            this.btnMasAntiguo.setVisible(true);
        } else {
           this.btnMasAntiguo.setVisible(false);
        }
        modeloListaProductos.clear();
        String partess[] = seleccionado.split("-");
        String lista=this.control.listarProductos(partess[0]);
        String partes[] = lista.split(";");
        for (int i = 0; i < partes.length; i++) {
            String dato = partes[i];
            modeloListaProductos.addElement(dato);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListSucursales = new javax.swing.JList<>();
        jPanelInformacion = new javax.swing.JPanel();
        txtAccionSucursal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnameSucursal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDireccionSucursal = new javax.swing.JTextField();
        btnAdSucursal = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListProductos = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAddSucursal = new javax.swing.JButton();
        jPanelLineaProducto = new javax.swing.JPanel();
        jAccionList = new javax.swing.JLabel();
        btnAdProducto = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPCodigo = new javax.swing.JTextField();
        txtPName = new javax.swing.JTextField();
        txtPDescripcion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPPrecio = new javax.swing.JTextField();
        btnOpcionProducto = new javax.swing.JButton();
        lblFechaADD = new javax.swing.JLabel();
        txtfechaADD = new javax.swing.JTextField();
        btnDescontinuarLinea = new javax.swing.JButton();
        btnDeleteSucursal = new javax.swing.JButton();
        btnMasAntiguo = new javax.swing.JButton();
        txtPO = new javax.swing.JLabel();
        btnSucursales = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jListSucursales.setBackground(new java.awt.Color(255, 255, 255));
        jListSucursales.setBorder(javax.swing.BorderFactory.createTitledBorder("Sucursales"));
        jListSucursales.setForeground(new java.awt.Color(0, 0, 0));
        jListSucursales.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListSucursales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListSucursalesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListSucursales);

        jPanelInformacion.setBackground(new java.awt.Color(255, 255, 255));
        jPanelInformacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtAccionSucursal.setBackground(new java.awt.Color(0, 0, 0));
        txtAccionSucursal.setForeground(new java.awt.Color(0, 0, 0));
        txtAccionSucursal.setText("Información de sucursal");

        jLabel2.setText("Nombre:");

        txtnameSucursal.setEditable(false);
        txtnameSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameSucursalActionPerformed(evt);
            }
        });

        jLabel3.setText("Direccion de la sucursal:");

        txtDireccionSucursal.setEditable(false);

        btnAdSucursal.setText("Agregar");
        btnAdSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdSucursalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInformacionLayout = new javax.swing.GroupLayout(jPanelInformacion);
        jPanelInformacion.setLayout(jPanelInformacionLayout);
        jPanelInformacionLayout.setHorizontalGroup(
            jPanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInformacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDireccionSucursal)
                    .addGroup(jPanelInformacionLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnameSucursal))
                    .addGroup(jPanelInformacionLayout.createSequentialGroup()
                        .addGroup(jPanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAccionSucursal)
                            .addComponent(jLabel3))
                        .addGap(0, 109, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInformacionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAdSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelInformacionLayout.setVerticalGroup(
            jPanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInformacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtAccionSucursal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtnameSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDireccionSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAdSucursal)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jListProductos.setBackground(new java.awt.Color(255, 255, 255));
        jListProductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jListProductos.setForeground(new java.awt.Color(0, 0, 0));
        jListProductos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListProductosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jListProductos);

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("UNIVERSIDAD FRANCISCO DE PAULA SANTANDER");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("EJERCICIO PRACTICO HIPERMERCADO ESTRUCTURA DE DATOS");

        btnAddSucursal.setBackground(new java.awt.Color(255, 255, 255));
        btnAddSucursal.setForeground(new java.awt.Color(0, 0, 0));
        btnAddSucursal.setText("Agregar Sucursal");
        btnAddSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSucursalActionPerformed(evt);
            }
        });

        jPanelLineaProducto.setBackground(new java.awt.Color(255, 255, 255));
        jPanelLineaProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jAccionList.setBackground(new java.awt.Color(0, 0, 0));
        jAccionList.setForeground(new java.awt.Color(0, 0, 0));
        jAccionList.setText("Nueva Linea de Producto");

        btnAdProducto.setText("Agregar");
        btnAdProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdProductoActionPerformed(evt);
            }
        });

        jLabel7.setText("Codigo:");

        jLabel8.setText("Nombre:");

        jLabel9.setText("Descripcion:");

        jLabel10.setText("Precio:");

        btnOpcionProducto.setText("Nuevo Producto");
        btnOpcionProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionProductoActionPerformed(evt);
            }
        });

        lblFechaADD.setText("Fecha ADD:");

        btnDescontinuarLinea.setText("Descontinuar Producto");
        btnDescontinuarLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescontinuarLineaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLineaProductoLayout = new javax.swing.GroupLayout(jPanelLineaProducto);
        jPanelLineaProducto.setLayout(jPanelLineaProductoLayout);
        jPanelLineaProductoLayout.setHorizontalGroup(
            jPanelLineaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLineaProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLineaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLineaProductoLayout.createSequentialGroup()
                        .addGroup(jPanelLineaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jAccionList)
                            .addGroup(jPanelLineaProductoLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPDescripcion))
                            .addGroup(jPanelLineaProductoLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelLineaProductoLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPName, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(45, 45, 45)
                        .addGroup(jPanelLineaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelLineaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanelLineaProductoLayout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtPPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btnOpcionProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDescontinuarLinea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanelLineaProductoLayout.createSequentialGroup()
                                .addComponent(lblFechaADD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtfechaADD, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 17, Short.MAX_VALUE))
                    .addComponent(btnAdProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelLineaProductoLayout.setVerticalGroup(
            jPanelLineaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLineaProductoLayout.createSequentialGroup()
                .addGroup(jPanelLineaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLineaProductoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jAccionList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLineaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtPCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelLineaProductoLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanelLineaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtPPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLineaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLineaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txtPName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLineaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblFechaADD)
                        .addComponent(txtfechaADD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelLineaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOpcionProducto))
                .addGroup(jPanelLineaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLineaProductoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(btnAdProducto)
                        .addContainerGap())
                    .addGroup(jPanelLineaProductoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDescontinuarLinea)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        btnDeleteSucursal.setBackground(new java.awt.Color(255, 255, 255));
        btnDeleteSucursal.setForeground(new java.awt.Color(0, 0, 0));
        btnDeleteSucursal.setText("Eliminar Sucursal");
        btnDeleteSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSucursalActionPerformed(evt);
            }
        });

        btnMasAntiguo.setBackground(new java.awt.Color(255, 255, 255));
        btnMasAntiguo.setForeground(new java.awt.Color(0, 0, 0));
        btnMasAntiguo.setText("Producto mas Antiguo");
        btnMasAntiguo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasAntiguoActionPerformed(evt);
            }
        });

        txtPO.setForeground(new java.awt.Color(0, 0, 0));
        txtPO.setText("Listado de Productos");

        btnSucursales.setBackground(new java.awt.Color(255, 255, 255));
        btnSucursales.setForeground(new java.awt.Color(0, 0, 0));
        btnSucursales.setText("Generar Reporte");
        btnSucursales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSucursalesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel5))
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnAddSucursal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                            .addComponent(btnDeleteSucursal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMasAntiguo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSucursales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanelInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPO))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanelLineaProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanelInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtPO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAddSucursal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteSucursal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMasAntiguo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSucursales)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelLineaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSucursalActionPerformed
       this.jPanelInformacion.setVisible(true);
       this.btnAdSucursal.setVisible(true);
       this.txtnameSucursal.setEditable(true);
       this.txtDireccionSucursal.setEditable(true);
       this.txtAccionSucursal.setText("Agregar Nueva Sucursal");
        this.jListProductos.setVisible(false);
        this.btnDescontinuarLinea.setVisible(false);
    }//GEN-LAST:event_btnAddSucursalActionPerformed

    private void txtnameSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameSucursalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameSucursalActionPerformed

    private void btnAdSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdSucursalActionPerformed
     this.control.agregarSucursal(this.txtnameSucursal.getText(), this.txtDireccionSucursal.getText());
     this.mostrarSucursales();
     limpiarCampos();
    }//GEN-LAST:event_btnAdSucursalActionPerformed

    private void jListSucursalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListSucursalesMouseClicked
        this.txtAccionSucursal.setText("Información sucursal");
        this.btnAdSucursal.setVisible(false);
        this.jListProductos.setVisible(true);
        seleccionado = jListSucursales.getSelectedValue();
        String partess[] = seleccionado.split("-");
        this.setCamposInformacion(partess[0], partess[1]);
        this.jPanelLineaProducto.setVisible(true);
        this.mostrarProductosSucursal();
        this.btnOpcionProducto.setVisible(false);
        this.lblFechaADD.setVisible(false);
        this.txtfechaADD.setVisible(false);
        this.btnMasAntiguo.setVisible(false);
    }//GEN-LAST:event_jListSucursalesMouseClicked

    private void btnAdProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdProductoActionPerformed
        String partes[]=seleccionado.split("-");
        String sucursal=partes[0];
        this.control.lanzarProducto(txtPName.getText(),txtPCodigo.getText(),txtPDescripcion.getText(),Double.parseDouble(txtPPrecio.getText()),sucursal);
        this.mostrarProductosSucursal();
        this.setearCamposProductos();
    }//GEN-LAST:event_btnAdProductoActionPerformed

    private void jListProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListProductosMouseClicked
       this.jAccionList.setText("Información de Producto");
       this.seleccionadosp=jListProductos.getSelectedValue();
       String partes[]=this.seleccionadosp.split("-");
       txtPCodigo.setText(partes[0]);
       txtPName.setText(partes[1]);
       txtPDescripcion.setText(partes[2]);
       txtPPrecio.setText(partes[3]);
       txtPCodigo.setEditable(false);
       txtPName.setEditable(false);
       txtPDescripcion.setEditable(false);
       txtPPrecio.setEditable(false);
       this.btnAdProducto.setVisible(false);
       this.btnOpcionProducto.setVisible(true);
       this.lblFechaADD.setVisible(true);
       this.txtfechaADD.setVisible(true);
       this.txtfechaADD.setEditable(false);
       this.txtfechaADD.setText(partes[4]);
       this.btnDescontinuarLinea.setVisible(true);
    }//GEN-LAST:event_jListProductosMouseClicked

    private void btnOpcionProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionProductoActionPerformed
       this.setearCamposProductos();
       txtPCodigo.setEditable(true);
       txtPName.setEditable(true);
       txtPDescripcion.setEditable(true);
       txtPPrecio.setEditable(true);
        this.btnAdProducto.setVisible(true);
        this.btnOpcionProducto.setVisible(false);
        this.btnDescontinuarLinea.setVisible(false);
    }//GEN-LAST:event_btnOpcionProductoActionPerformed

    private void btnDeleteSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSucursalActionPerformed
        String sucursal=JOptionPane.showInputDialog("Digite el nombre de la sucursal a eliminar");
       int seleccion=JOptionPane.showConfirmDialog(null, "¿Esta seguro de eliminar esa sucursal?");
       if(seleccion==0){
       this.control.eliminarSucursal(sucursal);
       this.mostrarProductosSucursal();
       this.mostrarSucursales();
       this.setearCamposProductos();
       this.limpiarCampos();
       this.jPanelLineaProducto.setVisible(false);
       }
       
    }//GEN-LAST:event_btnDeleteSucursalActionPerformed

    private void btnMasAntiguoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasAntiguoActionPerformed
       String antiguo=this.control.productoMasAntiguo();
       String partes[]=antiguo.split("-");
       this.setCamposProductos(partes[0],partes[1],partes[2],partes[3],partes[4]);
       btnMasAntiguo.setVisible(true);
    }//GEN-LAST:event_btnMasAntiguoActionPerformed

    private void btnDescontinuarLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescontinuarLineaActionPerformed
       String partesS[]=seleccionado.split("-");
       String partesSP[]=seleccionadosp.split("-");
       String sqk="¿Esta seguro de descontinuar el producto "+partesSP[0]+" de la sucursal "+partesS[0]+"?";
       int opcion=JOptionPane.showConfirmDialog(null, sqk);
       if(opcion==0){
        this.control.descontinuarProducto(partesSP[1],partesS[0]);
       this.setearCamposProductos();
       this.mostrarProductosSucursal();
       this.lblFechaADD.setText("");
       this.txtfechaADD.setText("");
       }
    }//GEN-LAST:event_btnDescontinuarLineaActionPerformed

    private void btnSucursalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSucursalesActionPerformed
        this.control.generarReporte();
    }//GEN-LAST:event_btnSucursalesActionPerformed
    
    public void setCamposProductos(String codigo,String name,String descripcion,String precio,String fechaADD){
        this.txtPCodigo.setText(codigo);
        this.txtPDescripcion.setText(descripcion);
        this.txtPPrecio.setText(precio);
        this.txtPName.setText(name);
        this.txtfechaADD.setText(fechaADD);
    }    
    public void setearCamposProductos(){
        this.txtPCodigo.setText("");
        this.txtPDescripcion.setText("");
        this.txtPPrecio.setText("");
        this.txtPName.setText("");
        this.txtfechaADD.setText("");
    }
    
    public void setCamposInformacion(String name,String direccion){
        this.txtnameSucursal.setText(name);
        this.txtDireccionSucursal.setText(direccion);
        this.txtnameSucursal.setEditable(false);
        this.txtDireccionSucursal.setEditable(false);
    }
    
    public void limpiarCampos(){
        this.txtDireccionSucursal.setText("");
        this.txtnameSucursal.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdProducto;
    private javax.swing.JButton btnAdSucursal;
    private javax.swing.JButton btnAddSucursal;
    private javax.swing.JButton btnDeleteSucursal;
    private javax.swing.JButton btnDescontinuarLinea;
    private javax.swing.JButton btnMasAntiguo;
    private javax.swing.JButton btnOpcionProducto;
    private javax.swing.JButton btnSucursales;
    private javax.swing.JLabel jAccionList;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jListProductos;
    private javax.swing.JList<String> jListSucursales;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelInformacion;
    private javax.swing.JPanel jPanelLineaProducto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblFechaADD;
    private javax.swing.JLabel txtAccionSucursal;
    private javax.swing.JTextField txtDireccionSucursal;
    private javax.swing.JTextField txtPCodigo;
    private javax.swing.JTextField txtPDescripcion;
    private javax.swing.JTextField txtPName;
    private javax.swing.JLabel txtPO;
    private javax.swing.JTextField txtPPrecio;
    private javax.swing.JTextField txtfechaADD;
    private javax.swing.JTextField txtnameSucursal;
    // End of variables declaration//GEN-END:variables
}
